DROP TABLE jokes;

CREATE TABLE jokes (
    id      NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    joke   VARCHAR2(8168) NOT NULL,
    PRIMARY KEY (id)
);

select * from jokes;


-- select count(*) from jokes;

-- commit;

